name: Test
run-name: Test repo ${{ inputs.override-repo }} commit ${{ inputs.override-commit }}
on:
  push:
  workflow_dispatch:
    inputs:
      override-repo:
        type: string
      override-commit:
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Latest Libs
        run: git submodule update --init --remote --recursive
      - name: Checkout Target Repo
        if: inputs.override-repo && inputs.override-commit
        env:
          OVERRIDE_REPO: ${{ inputs.override-repo }}
          OVERRIDE_COMMIT: ${{ inputs.override-commit }}
        run: git -C ${OVERRIDE_REPO##*/} checkout $OVERRIDE_COMMIT
      - name: Build Tests
        run: make tests -j7
      - name: Run Tests
        run: |
          make test TEST_SUMMARY=out/summary.md
          ./process out/summary.md >> $GITHUB_STEP_SUMMARY
  test-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: qemu-system-arm
      - uses: actions/checkout@v4
      - name: Use Latest Libs
        run: git submodule update --init --remote --recursive
      - name: Build Tests
        run: make tests -j7 TARGET=qemu-arm
      - name: Run Tests
        run: |
          make test TARGET=qemu-arm TEST_SUMMARY=out/summary.md
          ./process out/summary.md >> $GITHUB_STEP_SUMMARY
